package diploma.socialfaceapp.Utils;
// Generated Mar 24, 2017 3:38:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TmlDocumentsReviews generated by hbm2java
 */
public class TmlDocumentsReviews  implements java.io.Serializable {


     private TmlDocumentsReviewsId id;
     private String reviewValue;
     private Date reviewDate;

    public TmlDocumentsReviews() {
    }

	
    public TmlDocumentsReviews(TmlDocumentsReviewsId id, Date reviewDate) {
        this.id = id;
        this.reviewDate = reviewDate;
    }
    public TmlDocumentsReviews(TmlDocumentsReviewsId id, String reviewValue, Date reviewDate) {
       this.id = id;
       this.reviewValue = reviewValue;
       this.reviewDate = reviewDate;
    }
   
    public TmlDocumentsReviewsId getId() {
        return this.id;
    }
    
    public void setId(TmlDocumentsReviewsId id) {
        this.id = id;
    }
    public String getReviewValue() {
        return this.reviewValue;
    }
    
    public void setReviewValue(String reviewValue) {
        this.reviewValue = reviewValue;
    }
    public Date getReviewDate() {
        return this.reviewDate;
    }
    
    public void setReviewDate(Date reviewDate) {
        this.reviewDate = reviewDate;
    }




}


