package diploma.socialfaceapp.Utils;
// Generated Mar 24, 2017 3:38:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TmlDocuments generated by hbm2java
 */
public class TmlDocuments  implements java.io.Serializable {


     private String documentExternalid;
     private String documentTitle;
     private Date documentDate;
     private String documentType;
     private String documentUrl;
     private String documentContent;
     private int documentAnnotated;

    public TmlDocuments() {
    }

	
    public TmlDocuments(String documentExternalid, String documentTitle, Date documentDate, String documentType, String documentUrl, int documentAnnotated) {
        this.documentExternalid = documentExternalid;
        this.documentTitle = documentTitle;
        this.documentDate = documentDate;
        this.documentType = documentType;
        this.documentUrl = documentUrl;
        this.documentAnnotated = documentAnnotated;
    }
    public TmlDocuments(String documentExternalid, String documentTitle, Date documentDate, String documentType, String documentUrl, String documentContent, int documentAnnotated) {
       this.documentExternalid = documentExternalid;
       this.documentTitle = documentTitle;
       this.documentDate = documentDate;
       this.documentType = documentType;
       this.documentUrl = documentUrl;
       this.documentContent = documentContent;
       this.documentAnnotated = documentAnnotated;
    }
   
    public String getDocumentExternalid() {
        return this.documentExternalid;
    }
    
    public void setDocumentExternalid(String documentExternalid) {
        this.documentExternalid = documentExternalid;
    }
    public String getDocumentTitle() {
        return this.documentTitle;
    }
    
    public void setDocumentTitle(String documentTitle) {
        this.documentTitle = documentTitle;
    }
    public Date getDocumentDate() {
        return this.documentDate;
    }
    
    public void setDocumentDate(Date documentDate) {
        this.documentDate = documentDate;
    }
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }
    public String getDocumentUrl() {
        return this.documentUrl;
    }
    
    public void setDocumentUrl(String documentUrl) {
        this.documentUrl = documentUrl;
    }
    public String getDocumentContent() {
        return this.documentContent;
    }
    
    public void setDocumentContent(String documentContent) {
        this.documentContent = documentContent;
    }
    public int getDocumentAnnotated() {
        return this.documentAnnotated;
    }
    
    public void setDocumentAnnotated(int documentAnnotated) {
        this.documentAnnotated = documentAnnotated;
    }




}


