package diploma.socialfaceapp.Utils;
// Generated Mar 24, 2017 3:38:35 PM by Hibernate Tools 4.3.1



/**
 * TmlDocumentsReviewsId generated by hbm2java
 */
public class TmlDocumentsReviewsId  implements java.io.Serializable {


     private String documentExternalid;
     private String reviewAuthor;
     private String reviewName;

    public TmlDocumentsReviewsId() {
    }

    public TmlDocumentsReviewsId(String documentExternalid, String reviewAuthor, String reviewName) {
       this.documentExternalid = documentExternalid;
       this.reviewAuthor = reviewAuthor;
       this.reviewName = reviewName;
    }
   
    public String getDocumentExternalid() {
        return this.documentExternalid;
    }
    
    public void setDocumentExternalid(String documentExternalid) {
        this.documentExternalid = documentExternalid;
    }
    public String getReviewAuthor() {
        return this.reviewAuthor;
    }
    
    public void setReviewAuthor(String reviewAuthor) {
        this.reviewAuthor = reviewAuthor;
    }
    public String getReviewName() {
        return this.reviewName;
    }
    
    public void setReviewName(String reviewName) {
        this.reviewName = reviewName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TmlDocumentsReviewsId) ) return false;
		 TmlDocumentsReviewsId castOther = ( TmlDocumentsReviewsId ) other; 
         
		 return ( (this.getDocumentExternalid()==castOther.getDocumentExternalid()) || ( this.getDocumentExternalid()!=null && castOther.getDocumentExternalid()!=null && this.getDocumentExternalid().equals(castOther.getDocumentExternalid()) ) )
 && ( (this.getReviewAuthor()==castOther.getReviewAuthor()) || ( this.getReviewAuthor()!=null && castOther.getReviewAuthor()!=null && this.getReviewAuthor().equals(castOther.getReviewAuthor()) ) )
 && ( (this.getReviewName()==castOther.getReviewName()) || ( this.getReviewName()!=null && castOther.getReviewName()!=null && this.getReviewName().equals(castOther.getReviewName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDocumentExternalid() == null ? 0 : this.getDocumentExternalid().hashCode() );
         result = 37 * result + ( getReviewAuthor() == null ? 0 : this.getReviewAuthor().hashCode() );
         result = 37 * result + ( getReviewName() == null ? 0 : this.getReviewName().hashCode() );
         return result;
   }   


}


